# Generated by Django 6.0.1 on 2026-01-16 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlokVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='alok_images/')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('type', models.CharField(blank=True, choices=[('B', 'BLACK'), ('W', 'WHITE'), ('CH', 'CHOCOLATE')], max_length=2, null=True)),
            ],
        ),
    ]
