# Generated by Django 6.0.1 on 2026-01-16 17:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alok', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlokCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100)),
                ('issued_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('valit_untill', models.DateTimeField(blank=True, null=True)),
                ('alok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='alok.alokvarity')),
            ],
        ),
        migrations.CreateModel(
            name='AlokReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('type', models.CharField(blank=True, choices=[('B', 'BLACK'), ('W', 'WHITE'), ('CH', 'CHOCOLATE')], max_length=2, null=True)),
                ('alok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alok.alokvarity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
